### ISSUE TITLE
Export multiple selected into single FBX (Request)

### ISSUE THREAD

**Issue by alfandango** [nekorushi/Blender-FBX-Batch-Export#1]
Love the addon, has potential to save a lot of time in my workflow.  Just wondered if it's possible to have children exported into the same FBX as their parent object?  Currently all selected export as separate fbx files with no option to maintain parent/child relationship.

**Comment by nekorushi** [comment]
@alfandango hello! I am very happy to hear that you found the add-on useful.
I'm not sure at the moment but I think I can take look around the weekend.

In the meantime, if you have any ideas how would you like it to work UX-wise, please let me know. That would be very helpful.

Best regards

**Comment by alfandango** [comment]
That would be amazing!  Thankyou.

For the UX, just needs a tick box saying something like "Group hierarchies".  Selecting this would allow each parent or ungrouped object to be separated as a single fbx file.  The children are packaged with their parents.

EG, the following would export 3 FBX files:

Object 1 (parent)
- Object 2 (child)
- Object 3 (child)
- Object 4 (child)

Object 5 (parent)
- Object 6 (child)
- Object 7 (child)

Object 8 (no hierarchy)

**Comment by nekorushi** [comment]
@alfandango Please check out the newest version. Didn't do too much tests but seems to correctly do what you were describing. To export a nested group of objects, select only top parent. If you select any children, it will be also exported as separate group with their own children.

**Comment by alfandango** [comment]
Amazing - Works perfectly!  Thanks for implementing this :)

**Comment by nekorushi** [comment]
Awesome, great to hear that!
